name: Build Dylib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Theos
        run: git clone --recursive https://github.com/theos/theos.git ${{ github.workspace }}/theos

      - name: Build Project (Make)
        run: make clean all
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Compiled File
        uses: actions/upload-artifact@v4
        with:
          name: CHYAKO-Dylib
          path: .theos/obj/**/*.dylib
