name: Build Dylib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install and Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        env:
          THEOS: ~/theos

      - name: Build Project (Make)
        run: make clean all
        env:
          THEOS: ~/theos

      - name: Upload Compiled File
        uses: actions/upload-artifact@v4
        with:
          name: CHYAKO-Dylib
          path: .theos/obj/debug/*.dylib
